services:
  - type: web
    name: inbox-party-api
    runtime: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

  - type: web
    name: inbox-party-frontend
    runtime: static
    buildCommand: ""
    staticPublishPath: frontend
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://inbox-party-api.onrender.com/api/*
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=3600
