services:
  - type: web
    name: inbox-party-api
    runtime: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        value: postgresql://postgres:Playstation4%40@aws-0-us-east-1.pooler.supabase.com:6543/postgres?options=project%3Dzpoctgwpvuyftqhqitpx

  - type: web
    name: inbox-party-site
    runtime: static
    buildCommand: ""
    staticPublishPath: frontend
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://inbox-party-api-4swk.onrender.com/api/*
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=3600
